apiVersion: v1
kind: Service
metadata:
  labels:
    name: wordpress-mysql
  name: wordpress-mysql
  namespace: prd
spec:
  ports:
    - port: 3306
  selector:
    name: wordpress-mysql

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: wordpress-mysql
  name: wordpress-mysql
  namespace: prd
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wordpress-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress-mysql
    spec:
      nodeSelector:
        purpose: database
      restartPolicy: Always
      containers:
      - name: wordpress-mysql
        image: mysql:8.2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: wordpress-mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-efs-volume
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: passworduser
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: database
        resources:
            limits:
              cpu: 1024m
              memory: 2Gi
            requests:
              cpu: 256m
              memory: 1Gi
      volumes:
      - name: "mysql-efs-volume"
        persistentVolumeClaim:
          claimName: mysql-efs-pvc