apiVersion: v1
kind: Service
metadata:
  labels:
    app: welcome
  name: welcome
  namespace: prd
spec:
  type: NodePort
  ports:
    - name: "5051"
      port: 5051
      targetPort: 5051
      nodePort: 30101
  selector:
    app: welcome

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: welcome
  name: welcome
  namespace: prd
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: welcome
  template:
    metadata:
      labels:
        app: welcome
    spec:
      nodeSelector:
        purpose: applications
      restartPolicy: Always
      containers:
        - envFrom:
            - configMapRef:
                name: env-welcome
            #- secretRef:
            #    name: secrets-welcome
          image: AWS_ACCOUNT_ID.dkr.ecr.ap-southeast-1.amazonaws.com/welcome:build-e42594d7-a30e-43f1-91d0-f0b360d875a0
          imagePullPolicy: IfNotPresent
          name: welcome
          ports:
            - containerPort: 5051
          resources:
            limits:
              cpu: 1024m
              memory: 2Gi
            requests:
              cpu: 256m
              memory: 1Gi
