apiVersion: v1
kind: Secret
metadata:
  name: mysql-password
  namespace: prd
type: Opaque
data:
  password: cGR0bTJZZTZlc1NXTTVkdHdFWTczSEZwUQ==
  passworduser: SlRSTlBwYU02WTlXR2o4bmNnd2o0cVVDNA==
  username: d3BfdXNlcg==
  database: bXVsdGl0ZW5hbnRfd3A=
