apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-efs-pv
spec:
  capacity:
    storage: 6Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-xxxxx

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-efs-pvc
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: efs-sc
